Document: primordial-life
Title: Debian primordial-life Manual
Author: <insert document author here>
Abstract: This manual describes what primordial-life is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/primordial-life/primordial-life.sgml.gz

Format: postscript
Files: /usr/share/doc/primordial-life/primordial-life.ps.gz

Format: text
Files: /usr/share/doc/primordial-life/primordial-life.text.gz

Format: HTML
Index: /usr/share/doc/primordial-life/html/index.html
Files: /usr/share/doc/primordial-life/html/*.html
